{{- range $key, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: {{ $svc.name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
    spec:
      containers:
        - name: {{ $svc.name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          ports:
            - containerPort: {{ $svc.port }}
{{- if $svc.env }}
          env:
{{- range $envKey, $envValue := $svc.env }}
            - name: {{ $envKey }}
              value: {{ $envValue | quote }}
{{- end }}
{{- end }}
{{- if and $svc.persistence $svc.persistence.enabled }}
          volumeMounts:
            - name: {{ $svc.persistence.claimName }}
              mountPath: {{ $svc.persistence.mountPath | quote }}
{{- end }}
          resources:
{{ toYaml $svc.resources | indent 12 }}
{{- if $svc.probes.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $svc.probes.path }}
              port: {{ $svc.port }}
          livenessProbe:
            httpGet:
              path: {{ $svc.probes.path }}
              port: {{ $svc.port }}
{{- end }}
{{- if and $svc.persistence $svc.persistence.enabled }}
      volumes:
        - name: {{ $svc.persistence.claimName }}
          persistentVolumeClaim:
            claimName: {{ $svc.persistence.claimName }}
{{- end }}
---
{{- end }}
