{{- range $key, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $svc.name }}
  labels:
    app: {{ $svc.name }}
automountServiceAccountToken: false
---
{{- end }}
