{{- range $key, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
spec:
  type: {{ default "ClusterIP" $svc.type }}
  {{- if $svc.loadBalancerIP }}
  loadBalancerIP: {{ $svc.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ $svc.name }}
  ports:
    - port: {{ default $svc.port $svc.servicePort }}
      targetPort: {{ $svc.port }}
---
{{- end }}
